apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{service-name}}
  name: {{service-name}}-server
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - targetPort: 25565
    port: {{service-port}}
    protocol: TCP
  selector:
    app: {{service-name}}
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  type: LoadBalancer