apiVersion: v1
kind: Service
metadata:
  name: {{service-name}}-fw
  labels:
    app: {{service-name}}
spec:
  type: NodePort
  selector:
    app: {{service-name}}
  ports:
    - port: 25565
      targetPort: 25565